name: Python App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r app/requirements.txt
      - name: Lint
        run: |
          source .venv/bin/activate
          flake8 app/src
      - name: Test
        run: |
          source .venv/bin/activate
          pytest app/test
      - name: Package Azure Function App
        run: |
          cd app
          zip -r ../functionapp.zip .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: functionapp.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
